service: test-bot
frameworkVersion: '3'

custom:
  env: ${file(./env.json)}

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  profile: default
  environment: 
    PRIVATE_KEY: ${self:custom.env.PRIVATE_KEY}
    WEBHOOK_URL : ${self:custom.env.WEBHOOK_URL}
    NODE_PATH: "./:/opt/node_modules"
    ACCOUNT: ${self:custom.env.ACCOUNT}
    GENESIS_HEIGHT : ${self:custom.env.GENESIS_HEIGHT}
    GENESIS_TIME : ${self:custom.env.GENESIS_TIME}
package:
  patterns:
    - '!node_modules/**'

functions:
  bot_test:
    handler: handler.bot_test
    events:
      - httpApi:
          path: /bot
          method: post
    layers:
      - arn:aws:lambda:us-east-1:355730967926:layer:node-util-layer:latest
plugins:
  - serverless-latest-layer-version
